// <auto-generated />
namespace TriQuint.CheckList.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddTestCheckListItemTemplate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTestCheckListItemTemplate));
        
        string IMigrationMetadata.Id
        {
            get { return "201503051437333_AddTestCheckListItemTemplate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
